#!/bin/sh
save() {
  backup_dir=""
  if [ -z "$1" ]; then
    backup_file="./database.sql";
  else
    backup_file=$1
  fi

  $colors --magenta --newline "Saving database to '${backup_file}'"
  docker exec "${project}_database" sh -c "exec mysqldump --all-databases -uroot -p${database_password}" > "${backup_file}"
}

restore() {
  restore_file=""
  if [ -z "$1" ]; then
    restore_file="./database.sql";
  else
    restore_file=$1
  fi

  $colors --magenta --newline "Restoring database to '${restore_file}'"
  # docker exec -i "${project}_database" sh -c "mysql -uroot -p${database_password}" < "${restore_file}"
}

replace_prod() {
  replace_file=""

  if [ -z "$1" ]; then
    replace_file="./database.sql";
  else
    replace_file=$1
  fi

  $colors --magenta --newline "Substituting '${development_domain}' to '${production_domain}' in '${replace_file}'"
  sed -i.bak s/"${development_domain}"/"${production_domain}"/g $replace_file && rm -f "${replace_file}.bak"
}

replace_dev() {
  replace_file=""

  if [ -z "$1" ]; then
    replace_file="./database.sql";
  else
    replace_file=$1
  fi

  $colors --magenta --newline "Substituting '${production_domain}' to '${development_domain}' in '${replace_file}'"
  sed -i.bak s/"${production_domain}"/"${development_domain}"/g $replace_file && rm -f "${replace_file}.bak"
}


usage() {
cat << EOF
usage: wordpress database [options] <argv>...

Options:
  -h, --help          Show help options

Arguments:
  save                Creates a snapshot of the currently running database
  restore             Restores the database to the latest or a given state
  replace_prod        Replaces the local domain with the target domain
  replace_dev         Replaces the production domain with the local domain
EOF
}

for var in "$@"
do
    case $var in
    save)
      save $2
      exit
    ;;
    restore)
      restore $2
      exit
    ;;
    replace_prod)
      replace_prod $2
      exit
    ;;
    replace_dev)
      replace_dev $2
      exit
    ;;
    *)
      usage
    ;;
    esac
done

if [ -z ${1+x} ]; then usage; fi
