#!/bin/sh
compose_file="docker/dev.yml"

up() {
  $colors --yellow --newline "Starting project '${project}' dev environment on '${development_domain}'"
  docker-compose --file $compose_file up -d
}

down() {
  $colors --yellow --newline "Stopping project '${project}' dev environment"
  docker-compose --file $compose_file down
}

pause() {
  $colors --yellow --newline "Pausing project '${project}' dev environment"
  docker-compose --file $compose_file pause
}

unpause() {
  $colors --yellow --newline "Unpausing project '${project}' dev environment"
  docker-compose --file $compose_file unpause
}

restart() {
  $colors --yellow --newline "Restarting project '${project}' dev environment"
  docker-compose --file $compose_file restart
}

logs() {
  docker-compose --file $compose_file logs
}


usage() {
cat << EOF
usage: wordpress dev [options] <argv>...

Options:
  -h, --help          Show help options

Arguments:
  init                Initialises the dev environment, including a database restore
  up                  Starts the dev environment
  down                Saves the database and stops the dev environment
  kill                Stops the network
  pause               Pause the dev environment
  unpause             Unpause the dev environment
  restart             Restart the dev environment
EOF
}

for var in "$@"
do
    case $var in
    init)
      ./wordpress database replace_dev
      up
      exit
    ;;
    up)
      up
      exit
    ;;
    down)
      ./wordpress database save
      down
      exit
    ;;
    kill)
      down
      exit
    ;;
    pause)
      pause
      exit
    ;;
    unpause)
      unpause
      exit
    ;;
    restart)
      restart
      exit
    ;;
    logs)
      logs
      exit
    ;;
    *)
      usage
    ;;
    esac
done

if [ -z ${1+x} ]; then usage; fi

