#!/bin/sh
compose_file="docker/prod.yml"

up() {
  $colors --yellow --newline "Starting project '${project}' prododuction environment on '${production_domain}'"
  docker-compose --file $compose_file up -d
}

down() {
  $colors --yellow --newline "Stopping project '${project}' prododuction environment"
  docker-compose --file $compose_file down
}

restart() {
  $colors --yellow --newline "Restarting project '${project}' prododuction environment"
  docker-compose --file $compose_file restart
}

logs() {
  docker-compose --file $compose_file logs
}

usage() {
cat << EOF
usage: wordpress prod [options] <argv>...

Options:
  -h, --help          Show help options

Arguments:
  init                Initialises the prod environment, including a database restore
  up                  Starts the prod environment
  kill                Stops the network
  down                Saves the database and stops the prod environment
  restart             Restart the prod environment
EOF
}

for var in "$@"
do
    case $var in
    init)
      ./wordpress database replace_prod
      up
      exit
    ;;
    up)
      up
      exit
    ;;
    down)
      ./wordpress database save
      down
      exit
    ;;
    kill)
      down
      exit
    ;;
    restart)
      restart
      exit
    ;;
    logs)
      logs
      exit
    ;;
    *)
      usage
    ;;
    esac
done

if [ -z ${1+x} ]; then usage; fi

